### ISSUE TITLE
CRUD Endpoints for HealthOfficer Model

### ISSUE THREAD

**Issue by austinoski** [zuri-training/e-care-be-pjt-6#12]
Implement endpoints for Creating, Retrieving, Updating and Deleting Health Officers.
Endpoints should return data in json format.
Implement endpoints in api/views.py file and create the url routes in api/urls.py file.

## New Routes to be Added to api/urls.py file
**GET user/doctor/**  return all doctors **status - 200**
**GET user/doctor/uuid/**  return doctor with uuid **status - 200**
**POST user/doctor/**  create a new Health Officer  **status - 201**
**PATCH user/doctor/uuid/**  Update record of health officer with uuid
**DELETE user/doctor/uuid/**  Delete record of health officer with uuid

**Comment by austinoski** [comment]
Right now the models have no *UUid field* but I'll add that tonight. So you can use *id field* instead.
I'll update it when I add the *UUid field*

**Comment by blacdev** [comment]
I tried the PUT but i wasn't getting it. IT kept telling me "the field has to unique" and i did everything right.
